spring.application.name=task-service
server.port=${SERVER_PORT:5000}
order.service.base-url=${ORDER_SERVICE_URL:http://order-service:5000}
payment.service.base-url=${PAYMENT_SERVICE_URL:http://payment-service:5000}
cart.service.base-url=${CART_SERVICE_URL:http://cart-service:5000}
menu.service.base-url=${MENU_SERVICE_URL:http://menu-service:5000}